// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2013-2019 Ismael Hamed")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.3.10")]
[assembly: AssemblyFileVersionAttribute("1.3.10")]
